### PR TITLE
fix prefix option

### PR DESCRIPTION
**Pull request by michaelfung**
set prefix option according to etcd API

### CODE REVIEW

**Comment by foobargeez** [comment]
Your approach is much simpler and cleaner -- thanks.  I currently use a much-complicated solution :-/ -- something like below:

```
sub BinaryToASCII ($bin) {
  return unpack("A*", pack("B*", $bin));
}

$range_end = BinaryToASCII("0" . Math::BigInt->from_bin($range_key)->binc()->to_bin());
```

I should have raised a PR to be included in the module earlier (or a simplified version of it) :-/

**Review by hexfusion — COMMENTED** [review]
@michaelfung, thanks for the contribution! This looks good, could you also update the POD on the prefix accessor while we are here?
https://github.com/hexfusion/perl-net-etcd/blob/30a712767824d7e768f020f0143466d41669e00a/lib/Net/Etcd/Auth/RolePermission.pm#L99-L104

**Comment by hexfusion** [comment]
ref: https://github.com/hexfusion/perl-net-etcd/issues/53

**Review by hexfusion — APPROVED** [review]

**Comment by hexfusion** [comment]
@michaelfung, thanks again. I will cut a new release for CPAN Monday morning.

**Comment by hexfusion** [comment]
@michaelfung https://github.com/hexfusion/perl-net-etcd/releases/tag/v0.022 is on it's way to CPAN. Thanks again!

**Pull request merged**
